### ISSUE TITLE
Will you release the code recently?

### ISSUE THREAD

**Issue by LEELLL** [Aubrey-ao/HumanBehaviorAnimation#2]
Excellent job! I am looking forward to the code release.

**Comment by youngstu** [comment]
Wonderful work! Look forward to the code release too.

**Comment by Aubrey-ao** [comment]
Please check this issue: #1 .

**Comment by Aubrey-ao** [comment]
A [simplified version](https://github.com/Aubrey-ao/HumanBehaviorAnimation/tree/main/HumanBehaviorAnimation/RhythmicGesticulator/Simplified_Version) has been approved for release. If have any problem to improve the performance, plz contact me : )
