### ISSUE TITLE
 Look forward to the code release.

### ISSUE THREAD

**Issue by youngstu** [Aubrey-ao/HumanBehaviorAnimation#3]
Excellent Job.  Look forward to the code release. Thans.

**Comment by Aubrey-ao** [comment]
Please check this issue: #1 .

**Comment by Aubrey-ao** [comment]
A [simplified version](https://github.com/Aubrey-ao/HumanBehaviorAnimation/tree/main/HumanBehaviorAnimation/RhythmicGesticulator/Simplified_Version) has been approved for release. If have any problem to improve the performance, plz contact me : )
