### ISSUE TITLE
Recommend GestureMaster, it looks nice

### ISSUE THREAD

**Issue by youngstu** [Aubrey-ao/HumanBehaviorAnimation#5]
GestureMaster: graph-based speech-driven gesture generation.

**Comment by hmthanh** [comment]
I'm waiting for your code every day. Please check email. Thanks

**Comment by Aubrey-ao** [comment]
Thanks for the kind recommendation. The question about the code release have been discussed in issue #1 , this issue will be closed.

**Comment by Aubrey-ao** [comment]
Thanks for the kind recommendation. The question about the code release have been discussed in issue #1 , this issue will be closed.
