### ISSUE TITLE
eagerly awaiting

### ISSUE THREAD

**Issue by boyuaner** [Aubrey-ao/HumanBehaviorAnimation#6]
Very inspiring work! If there's any plan to release the code recently? Would you consider releasing the main model code for reference first, then release the rest later? Thank you.

**Comment by Aubrey-ao** [comment]
A [simplified version](https://github.com/Aubrey-ao/HumanBehaviorAnimation/tree/main/HumanBehaviorAnimation/RhythmicGesticulator/Simplified_Version) has been approved for release. If have any problem to improve the performance, plz contact me : )
