### ISSUE TITLE
when would the code be released?

### ISSUE THREAD

**Issue by MengHao666** [Aubrey-ao/HumanBehaviorAnimation#7]
You said "Coming soon...". That is a lie.

**Comment by Aubrey-ao** [comment]
A [simplified version](https://github.com/Aubrey-ao/HumanBehaviorAnimation/tree/main/HumanBehaviorAnimation/RhythmicGesticulator/Simplified_Version) has been approved for release. If have any problem to improve the performance, plz contact me : )
